'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Namespace Asp.NETMVCCRUD

    Partial Public Class DBModel
        Inherits DbContext
    
        Public Sub New()
            MyBase.New("name=DBModel")
        End Sub
    
        Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
            Throw New UnintentionalCodeFirstException()
        End Sub
    
        Public Overridable Property TabelaPedido() As DbSet(Of TabelaPedido)
        Public Overridable Property TabelaProduto() As DbSet(Of TabelaProduto)
    
    End Class

End Namespace
