'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Asp.NETMVCCRUD

    Partial Public Class TabelaProduto
        Public Property Id As Integer
        Public Property Nome As String
        Public Property Quantidade As Nullable(Of Integer)
        Public Property Valor As Nullable(Of Decimal)
        Public Property Desconto As String
    
        Public Overridable Property TabelaPedido As ICollection(Of TabelaPedido) = New HashSet(Of TabelaPedido)
    
    End Class

End Namespace
