'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Asp.NETMVCCRUD

    Partial Public Class TabelaPedido
        Public Property Id As Integer
        Public Property data As Nullable(Of Date)
        Public Property descricao As String
        Public Property situacao As Nullable(Of Byte)
        Public Property FKTabelaProduto As Integer
    
        Public Overridable Property TabelaProduto As TabelaProduto
    
    End Class

End Namespace
